In [4]:
import pandas as pd
df=pd.read_csv('/Users/couet-lannesandre/Desktop/Formation/DVC/examen-dvc-1/data/raw_data/raw.csv')
df.head()

,date,ave_flot_air_flow,ave_flot_level,iron_feed,starch_flow,amina_flow,ore_pulp_flow,ore_pulp_pH,ore_pulp_density,silica_concentrate
0,2017-04-24 00:00:00,300.263166,383.982443,55.17,1979.589150,599.676489,400.017222,9.774028,1.753206,4.360000
1,2017-04-24 01:00:00,299.782402,386.049069,55.17,1758.466329,600.043100,400.484528,9.539246,1.754190,3.290000
2,2017-04-24 02:00:00,299.750052,385.250935,55.17,2379.752428,599.948406,400.325617,9.434227,1.756873,4.900000
3,2017-04-24 03:00:00,299.997522,389.635519,55.17,2287.130046,599.580383,399.801506,9.725607,1.727125,4.860153
4,2017-04-24 04:00:00,300.005220,387.810807,55.17,2291.789167,599.871217,399.567333,9.845198,1.633063,4.780898

In [ ]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

RAW_PATH = "examen_dvc/data/raw/raw.csv"
PROC_DIR = "examen_dvc/data/processed"

os.makedirs(PROC_DIR, exist_ok=True)

# La cible est en derni√®re colonne: silica_concentrate
df = pd.read_csv(RAW_PATH)
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

X_train.to_csv(os.path.join(PROC_DIR, "X_train.csv"), index=False)
X_test.to_csv(os.path.join(PROC_DIR, "X_test.csv"), index=False)
y_train.to_csv(os.path.join(PROC_DIR, "y_train.csv"), index=False)
y_test.to_csv(os.path.join(PROC_DIR, "y_test.csv"), index=False)
print("Split OK.")